on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

name: build test

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout docker/cli
        uses: actions/checkout@v2
        with:
          repository: docker/cli
          ref: v20.10.8
          path: cli
      - name: checkout docker-cli-windows
        uses: actions/checkout@v2
        with:
          repository: ionash/docker-cli-windows
          ref: ${{github.event.pull_request.head.ref}}
          path: docker-cli-windows
      - name: confirm files
        run: ls docker-cli-windows
      - name: copy files
        run: cp -rf docker-cli-windows/scripts cli
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: create builder
        run: sudo docker buildx create --use
      - name: build binary
        working-directory: ./cli
        run: sudo docker buildx bake --set binary.platform=windows/amd64
      - name: change asset owner
        working-directory: ./cli
        run: sudo chown -R runner:docker build
      - name: confirm build
        working-directory: ./cli/build
        run: ls
